version: "3"
services:
  zookeeper:
    image: awsazuser/zkpr349rh7
    deploy:
      placement:
        constraints: [node.role == manager]
    hostname: zookeeper
    ports:
    - "2181:2181"
    networks:
      - nifinw
  nifi:
    image: nifi:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - nifinw
networks:
  nifinw:
