version: "3"
services:
  zookeeper1:
    image: awsazuser/zkpr349rh7
    deploy:
      placement:
        constraints: [node.role == manager]
    hostname: zookeeper1
    ports:
     - "2181:2181"
    networks:
      - nifinw
  nifi:
    image: awsazuser/nifi:latest
    depends_on:
      - zookeeper1
    deploy:
      replicas: 5
    ports:
     - "8080:8080"
     - "8081:8081"
     - "8082:8082"
    networks:
      - nifinw

networks:
  nifinw:
